name: Update Profile Assets

on:
  schedule:
    - cron: "0 */24 * * *" # Roda todo dia
  workflow_dispatch: # Permite rodar manual
  push:
    branches:
      - main
    paths-ignore:
      - "assets/**"

permissions:
  contents: write # Essencial para o bot conseguir salvar as imagens

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x" # Versão mais estável
          cache: "npm"

      - name: Install Dependencies
        run: npm install # Usa o seu package.json organizado

      - name: Generate Assets
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          npm run generate:all

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/contrib-city.svg assets/my-lang-stats.svg
          git commit -m "chore: update profile assets [skip ci]" || echo "Sem mudanças para salvar"
          git push

          
